version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-mactwo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
